### ISSUE TITLE
setup GitHub action to always build Binder

### ISSUE THREAD

**Issue by erwanp** [radis/radis-lab#16]
Implement this : 

https://github.com/marketplace/actions/trigger-binder-build

Note : 

> Since binder is an none profit project, please use this action sparsely and in a none spammy manner, to treat their resources with care.

👉 let's only use on `main` branch.

### Implementation

I'm not used to Github Actions, but I think we can use this : 

```
name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - main

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: radis/radis-lab
```

---

*Not directly related : afterwards we'll probably also use GitHub Actions to build a part of the docker and reduce the charge on Binder. See #13*
